### ISSUE TITLE
When using renaming option provide option to prepend number to original name

### ISSUE THREAD

**Issue by basiclines** [basiclines/figma-super-tidy#17]
> The renaming function is very practical, but after renaming, the layers only have numbers, which is a pity.
>
>Can I keep the layer name? 
>Thank you!

**Comment by kamelohr** [comment]
@basiclines I just stumbled upon your cool plugin during the search of a Figma equivalent of this plugin for Sketch: https://github.com/romannurik/Sketch-ArtboardTricks 

There the rename function seem to work as intended by ChienWu in the Figma community. 
Let's say you have Artboards(Sketch)/Frames(Figma) in your file called:

DesktopView1, DesktopView2, 
PhoneView1, PhoneView2 etc.
Then after you ran the rename function of the plugin, they should be renamed to

100_DesktopView1, 101_DesktopView2
200_PhoneView1, 201_PhoneView2

(or starting with 000 instead of 100, respectively).

At least that's the behaviour of the function, I would appreciate. Hope this clarifies things :-)

**Comment by basiclines** [comment]
> At least that's the behaviour of the function, I would appreciate. Hope this clarifies things :-)
Helps a lot thank you @kamelohr. Will work on some preferences for the plugin so you can configure them at once

**Comment by basiclines** [comment]
Adding another verbatim:

> I would also like that renaming feature to only add the numbers as prefix, not to fully rename the frame. 😁
> For example:
> 000@old-layer-name
> 100@another-layer

> I believe that I use it everyday. I'm not sure, because is part of my workflow to use it, is in my muscle memory.

> Thank you for the time and effort you dedicated to develop it! ❤️
